######################################################################
# Automatically generated by qmake (3.0) 21 11:05:56 2016
######################################################################

QT += core gui
QT += widgets

TEMPLATE = app
TARGET = buss32054
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
    mainwindow.cpp

HEADERS += \
    mainwindow.h
